
export interface BlogPost {
  id: number;
  slug: string;
  title: string;
  summary: string;
  content: string;
  imageUrl: string;
  imageHint: string;
  photographer: string;
  photographerUrl: string;
  views: number;
  likes: number;
  shares: number;
  status: 'published' | 'draft' | 'private' | 'password-protected';
  lastUpdated: string;
  metaTitle?: string;
  metaDescription?: string;
  focusKeywords?: string[];
  seoScore?: number;
}

const getDateAgo = (days: number): string => {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date.toISOString();
}

const placeholderContent = `\n\nThis is a continuation of the article. Further points are discussed in detail here, providing more insights and information on the topic. We explore various aspects and provide a comprehensive overview for the reader.\n\nOur analysis delves deeper into the subject matter, offering examples and case studies to illustrate the key takeaways. We believe this thorough approach will help you better understand the complexities involved. Thank you for reading.`;


export const blogPosts: BlogPost[] = [
  {
    id: 1,
    slug: 'top-10-eco-friendly-products',
    title: 'Top 10 Eco-Friendly Products for Your Home',
    summary: 'As more and more people become aware of the impact that our lifestyles have on the environment, the demand for eco-friendly products is on the rise.',
    content: 'As more and more people become aware of the impact that our lifestyles have on the environment, the demand for eco-friendly products is on the rise.' + placeholderContent,
    imageUrl: 'https://images.pexels.com/photos/4108715/pexels-photo-4108715.jpeg?auto=compress&cs=tinysrgb&h=400&w=600&fit=crop',
    imageHint: 'eco friendly products',
    photographer: 'Sarah Chai',
    photographerUrl: 'https://www.pexels.com/@sarah-chai-1994500/',
    views: 1200,
    likes: 345,
    shares: 89,
    status: 'published',
    lastUpdated: getDateAgo(1),
    metaTitle: '10 Must-Have Eco-Friendly Home Products',
    metaDescription: 'Discover the top 10 eco-friendly products that can help you create a more sustainable and environmentally conscious home. Start making a difference today.',
    focusKeywords: ['eco-friendly products', 'sustainable home', 'green living'],
    seoScore: 85,
  },
  {
    id: 2,
    slug: 'impact-of-climate-change',
    title: 'The Impact of Climate Change on Biodiversity',
    summary: 'Climate change is one of the most pressing issues facing our planet today. Rising temperatures, extreme weather events, and sea-level rise are threatening ecosystems worldwide.',
    content: 'Climate change is one of the most pressing issues facing our planet today. Rising temperatures, extreme weather events, and sea-level rise are threatening ecosystems worldwide.' + placeholderContent,
    imageUrl: 'https://images.pexels.com/photos/14751274/pexels-photo-14751274.jpeg?auto=compress&cs=tinysrgb&h=400&w=600&fit=crop',
    imageHint: 'climate change biodiversity',
    photographer: 'Pexels',
    photographerUrl: 'https://www.pexels.com',
    views: 2500,
    likes: 780,
    shares: 150,
    status: 'published',
    lastUpdated: getDateAgo(3),
    metaTitle: 'How Climate Change Affects Global Biodiversity',
    metaDescription: 'Explore the profound impact of climate change on biodiversity, from coral reefs to rainforests. Understand the threats and what can be done to protect our planet.',
    focusKeywords: ['climate change', 'biodiversity', 'ecosystems', 'environmental impact'],
    seoScore: 92,
  },
  {
    id: 3,
    slug: 'benefits-of-sustainable-business',
    title: 'The Benefits of Sustainable Business Practices',
    summary: 'Sustainability has become an increasingly important issue for businesses in recent years. Adopting sustainable practices is not just good for the environment, it’s good for business.',
    content: 'Sustainability has become an increasingly important issue for businesses in recent years. Adopting sustainable practices is not just good for the environment, it’s good for business.' + placeholderContent,
    imageUrl: 'https://images.pexels.com/photos/380769/pexels-photo-380769.jpeg?auto=compress&cs=tinysrgb&h=400&w=600&fit=crop',
    imageHint: 'sustainable business',
    photographer: 'Jopwell',
    photographerUrl: 'https://www.pexels.com/@jopwell/',
    views: 850,
    likes: 210,
    shares: 45,
    status: 'draft',
    lastUpdated: getDateAgo(0),
    metaTitle: 'Why Sustainable Business is Good for Business',
    metaDescription: 'Learn about the key benefits of adopting sustainable business practices, from improved brand reputation to increased profitability and long-term success.',
    focusKeywords: ['sustainable business', 'corporate sustainability', 'green business'],
    seoScore: 78,
  },
   {
    id: 4,
    slug: 'the-psychology-of-color-in-marketing',
    title: 'The Psychology of Color in Marketing',
    summary: 'Discover how different colors influence consumer behavior and how you can use this knowledge to create more effective marketing campaigns.',
    content: 'Discover how different colors influence consumer behavior and how you can use this knowledge to create more effective marketing campaigns.' + placeholderContent,
    imageUrl: 'https://images.pexels.com/photos/399161/pexels-photo-399161.jpeg?auto=compress&cs=tinysrgb&h=400&w=600&fit=crop',
    imageHint: 'color marketing psychology',
    photographer: 'Designecologist',
    photographerUrl: 'https://www.pexels.com/@designecologist/',
    views: 3100,
    likes: 950,
    shares: 220,
    status: 'published',
    lastUpdated: getDateAgo(5),
    metaTitle: 'Color Psychology in Marketing: A Complete Guide',
    metaDescription: 'A deep dive into the psychology of color in marketing. Learn how colors like red, blue, and green can influence purchasing decisions and brand perception.',
    focusKeywords: ['color psychology', 'marketing', 'consumer behavior', 'branding'],
    seoScore: 88,
  },
  {
    id: 5,
    slug: 'a-guide-to-minimalist-wardrobe-palettes',
    title: 'A Guide to Minimalist Wardrobe Palettes',
    summary: 'Learn how to build a stylish and versatile wardrobe with a limited color palette. Simplify your life and always look put-together.',
    content: 'Learn how to build a stylish and versatile wardrobe with a limited color palette. Simplify your life and always look put-together.' + placeholderContent,
    imageUrl: 'https://images.pexels.com/photos/10404244/pexels-photo-10404244.jpeg?auto=compress&cs=tinysrgb&h=400&w=600&fit=crop',
    imageHint: 'minimalist wardrobe',
    photographer: 'Lana Fashion',
    photographerUrl: 'https://www.pexels.com/@lana-fashion-102575258/',
    views: 1800,
    likes: 560,
    shares: 110,
    status: 'private',
    lastUpdated: getDateAgo(8),
    metaTitle: 'How to Create a Minimalist Wardrobe Color Palette',
    metaDescription: 'Our guide to building a minimalist wardrobe. Learn how to choose a versatile color palette that simplifies your style and elevates your look.',
    focusKeywords: ['minimalist wardrobe', 'color palette', 'capsule wardrobe', 'fashion'],
    seoScore: 82,
  },
  {
    id: 6,
    slug: 'how-interior-colors-affect-your-mood',
    title: 'How Interior Colors Can Affect Your Mood',
    summary: 'The colors you choose for your home can have a significant impact on your emotions and well-being. Find the perfect shades for a happy home.',
    content: 'The colors you choose for your home can have a significant impact on your emotions and well-being. Find the perfect shades for a happy home.' + placeholderContent,
    imageUrl: 'https://images.pexels.com/photos/1080721/pexels-photo-1080721.jpeg?auto=compress&cs=tinysrgb&h=400&w=600&fit=crop',
    imageHint: 'interior design colors',
    photographer: 'Veejay Villafranca',
    photographerUrl: 'https://www.pexels.com/@veejay-villafranca-75573/',
    views: 1500,
    likes: 420,
    shares: 95,
    status: 'password-protected',
    lastUpdated: getDateAgo(10),
    metaTitle: 'Using Interior Colors to Boost Your Mood',
    metaDescription: 'Explore the connection between interior design colors and your mood. Learn which colors can make you feel happy, calm, or energized in your own home.',
    focusKeywords: ['interior design', 'color theory', 'home decor', 'mood'],
  },
  {
    id: 7,
    slug: 'figerout-in-daily-life',
    title: 'Beyond Design: Fun and Practical Ways to Use Figerout Every Day',
    summary: 'Discover how Figerout can brighten your daily tasks and bring a new level of fun to your routines. From matching your outfit to planning a party, learn how capturing colors can make the mundane magical.',
    content: 'Discover how Figerout can brighten your daily tasks and bring a new level of fun to your routines. From matching your outfit to planning a party, learn how capturing colors can make the mundane magical.' + placeholderContent,
    imageUrl: 'https://images.pexels.com/photos/7973302/pexels-photo-7973302.jpeg?auto=compress&cs=tinysrgb&h=400&w=600&fit=crop',
    imageHint: 'colorful daily life',
    photographer: 'Liza Summer',
    photographerUrl: 'https://www.pexels.com/@liza-summer/',
    views: 980,
    likes: 250,
    shares: 60,
    status: 'published',
    lastUpdated: getDateAgo(0),
    metaTitle: 'Practical and Fun Uses for the Figerout App',
    metaDescription: 'Figerout isn\'t just for designers! Discover fun and practical ways to use our color-capturing app in your daily life, from fashion to event planning.',
    focusKeywords: ['Figerout app', 'daily uses', 'color matching', 'creative apps'],
  },
  {
    id: 8,
    slug: 'the-role-of-color-in-creating-brand-identity',
    title: 'The Role of Color in Creating Brand Identity',
    summary: 'Explore how major brands use color to build recognition and evoke emotion.',
    content: 'Explore how major brands use color to build recognition and evoke emotion.' + placeholderContent,
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'brand identity',
    photographer: 'AI Generator',
    photographerUrl: '#',
    views: 0,
    likes: 0,
    shares: 0,
    status: 'draft',
    lastUpdated: getDateAgo(0),
    metaTitle: 'Brand Identity and Color: A Deep Dive',
    metaDescription: 'Learn how color theory is a cornerstone of brand identity, influencing consumer perception and brand loyalty. See examples from top companies.',
    focusKeywords: ['brand identity', 'color theory', 'marketing', 'logo design'],
    seoScore: 78,
  },
  {
    id: 9,
    slug: 'how-to-use-a-monochromatic-color-scheme-in-web-design',
    title: 'How to Use a Monochromatic Color Scheme in Web Design',
    summary: 'A practical guide to creating elegant and effective websites using a single color family.',
    content: 'A practical guide to creating elegant and effective websites using a single color family.' + placeholderContent,
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'web design',
    photographer: 'AI Generator',
    photographerUrl: '#',
    views: 0,
    likes: 0,
    shares: 0,
    status: 'draft',
    lastUpdated: getDateAgo(0),
    metaTitle: 'Web Design Guide: Monochromatic Color Schemes',
    metaDescription: 'Master the art of monochromatic web design. Our guide provides tips, examples, and best practices for creating a visually stunning website.',
    focusKeywords: ['web design', 'monochromatic', 'color scheme', 'UI/UX'],
    seoScore: 82,
  },
  {
    id: 10,
    slug: 'color-trends-to-watch-in-2025',
    title: 'Color Trends to Watch in 2025',
    summary: 'A forecast of the colors that will dominate fashion, interior design, and digital media in the coming year.',
    content: 'A forecast of the colors that will dominate fashion, interior design, and digital media in the coming year.' + placeholderContent,
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'color trends',
    photographer: 'AI Generator',
    photographerUrl: '#',
    views: 0,
    likes: 0,
    shares: 0,
    status: 'draft',
    lastUpdated: getDateAgo(0),
    metaTitle: '2025 Color Trends: What to Expect',
    metaDescription: 'Get ahead of the curve with our forecast for the biggest color trends of 2025. From earthy tones to vibrant hues, see what\'s next in design.',
    focusKeywords: ['color trends', '2025 forecast', 'design trends', 'interior design'],
    seoScore: 85,
  },
  {
    id: 11,
    slug: 'the-importance-of-accessibility-in-color-choices',
    title: 'The Importance of Accessibility in Color Choices',
    summary: 'Why designing for color blindness and other visual impairments is crucial for inclusive user experiences.',
    content: 'Why designing for color blindness and other visual impairments is crucial for inclusive user experiences.' + placeholderContent,
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'accessibility design',
    photographer: 'AI Generator',
    photographerUrl: '#',
    views: 0,
    likes: 0,
    shares: 0,
    status: 'draft',
    lastUpdated: getDateAgo(0),
    metaTitle: 'Accessible Design: Choosing Colors for Everyone',
    metaDescription: 'Learn how to make your designs more inclusive by choosing accessible color palettes. Understand WCAG guidelines and test your designs.',
    focusKeywords: ['accessibility', 'color contrast', 'inclusive design', 'WCAG'],
    seoScore: 90,
  },
  {
    id: 12,
    slug: 'using-figerout-to-create-perfect-social-media-graphics',
    title: 'Using Figerout to Create Perfect Social Media Graphics',
    summary: 'A step-by-step tutorial on using real-world colors captured with Figerout to design stunning social media posts.',
    content: 'A step-by-step tutorial on using real-world colors captured with Figerout to design stunning social media posts.' + placeholderContent,
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'social media',
    photographer: 'AI Generator',
    photographerUrl: '#',
    views: 0,
    likes: 0,
    shares: 0,
    status: 'draft',
    lastUpdated: getDateAgo(0),
    metaTitle: 'Figerout Tutorial: Elevate Your Social Media',
    metaDescription: 'Turn real-world inspiration into beautiful social media graphics with Figerout. This tutorial shows you how to capture colors and use them in your designs.',
    focusKeywords: ['Figerout app', 'social media design', 'color palette', 'content creation'],
    seoScore: 75,
  },
  {
    id: 13,
    slug: 'the-history-of-the-color-blue',
    title: 'The History of the Color Blue',
    summary: 'From ancient Egypt to modern art, explore the fascinating history and cultural significance of the color blue.',
    content: 'From ancient Egypt to modern art, explore the fascinating history and cultural significance of the color blue.' + placeholderContent,
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'blue history',
    photographer: 'AI Generator',
    photographerUrl: '#',
    views: 0,
    likes: 0,
    shares: 0,
    status: 'draft',
    lastUpdated: getDateAgo(0),
    metaTitle: 'A Brief History of the Color Blue',
    metaDescription: 'Journey through time and discover the rich history of the color blue, from its rare origins to its status as the world\'s favorite color.',
    focusKeywords: ['color history', 'blue', 'art history', 'cultural significance'],
    seoScore: 81,
  },
  {
    id: 14,
    slug: 'diy-home-decor-painting-with-a-bold-color-palette',
    title: 'DIY Home Decor: Painting with a Bold Color Palette',
    summary: 'Tips and inspiration for transforming a room in your home using a bold and expressive color palette.',
    content: 'Tips and inspiration for transforming a room in your home using a bold and expressive color palette.' + placeholderContent,
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'diy decor',
    photographer: 'AI Generator',
    photographerUrl: '#',
    views: 0,
    likes: 0,
    shares: 0,
    status: 'draft',
    lastUpdated: getDateAgo(0),
    metaTitle: 'DIY Home Decor: How to Use Bold Colors',
    metaDescription: 'Ready for a change? This guide provides DIY tips for using bold color palettes to create a statement in any room of your house.',
    focusKeywords: ['DIY home decor', 'painting', 'bold colors', 'interior design'],
    seoScore: 79,
  },
  {
    id: 15,
    slug: 'how-artists-use-color-to-convey-emotion',
    title: 'How Artists Use Color to Convey Emotion',
    summary: 'An analysis of famous artworks and how painters throughout history have used color to tell stories and evoke feelings.',
    content: 'An analysis of famous artworks and how painters throughout history have used color to tell stories and evoke feelings.' + placeholderContent,
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'art emotion',
    photographer: 'AI Generator',
    photographerUrl: '#',
    views: 0,
    likes: 0,
    shares: 0,
    status: 'draft',
    lastUpdated: getDateAgo(0),
    metaTitle: 'The Emotional Power of Color in Art',
    metaDescription: 'Explore how renowned artists masterfully use color to evoke specific emotions. A deep dive into the emotional language of the color wheel.',
    focusKeywords: ['color in art', 'art analysis', 'emotional response', 'famous painters'],
    seoScore: 83,
  },
  {
    id: 16,
    slug: 'matching-your-makeup-to-your-outfit-with-figerout',
    title: 'Matching Your Makeup to Your Outfit with Figerout',
    summary: 'A fun guide on how to use the Figerout app to perfectly coordinate your makeup look with the colors in your outfit.',
    content: 'A fun guide on how to use the Figerout app to perfectly coordinate your makeup look with the colors in your outfit.' + placeholderContent,
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'makeup fashion',
    photographer: 'AI Generator',
    photographerUrl: '#',
    views: 0,
    likes: 0,
    shares: 0,
    status: 'draft',
    lastUpdated: getDateAgo(0),
    metaTitle: 'Perfect Color Coordination: Makeup & Outfits with Figerout',
    metaDescription: 'Use Figerout to find the exact shades in your outfit and create a perfectly coordinated makeup look. A fun guide for fashion lovers.',
    focusKeywords: ['makeup', 'fashion', 'color matching', 'Figerout app'],
    seoScore: 77,
  },
  {
    id: 17,
    slug: 'the-science-of-light-and-color-perception',
    title: 'The Science of Light and Color Perception',
    summary: 'Understand the physics behind how we see color, from wavelengths of light to the way our brains interpret them.',
    content: 'Understand the physics behind how we see color, from wavelengths of light to the way our brains interpret them.' + placeholderContent,
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'science light',
    photographer: 'AI Generator',
    photographerUrl: '#',
    views: 0,
    likes: 0,
    shares: 0,
    status: 'draft',
    lastUpdated: getDateAgo(0),
    metaTitle: 'The Science of Seeing Color: Light and Perception',
    metaDescription: 'Ever wonder how we perceive color? This article breaks down the science of light waves, photoreceptors, and how our brain creates the colorful world we see.',
    focusKeywords: ['color science', 'light physics', 'perception', 'how we see color'],
    seoScore: 86,
  },
];
